# Generated by Django 3.2.23 on 2023-12-14 12:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20231201_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alternative_company_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternative contact number for the company.', max_length=128, null=True, region='GB'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_bio',
            field=models.TextField(blank=True, help_text='Provide a brief bio about your company.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_email',
            field=models.EmailField(blank=True, help_text='Enter your company contact email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary contact number for the company.', max_length=128, null=True, region='GB'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default='Asm me what my company name is...', help_text='Enter your company name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_services_post',
            field=models.TextField(blank=True, help_text='Post about your company services.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True, help_text='Enter your company website URL.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Your personal contact number.', max_length=128, null=True, region='GB', unique=True),
        ),
    ]
